id: P9D118FD8
initial_creation_type: ocr
source_metadata:
  volumes:
    078b812946574d83affb8a56fee55c2c:
      base_file: v098.txt
      image_group_id: I1PD95943
      title: རྒྱུད་གཞན་གྲུབ་པ་ཞེས་བྱ་བའི་རབ་ཏུ་བྱེད་པ།
      total_pages: 1825
      volume_number: 98
