id: D9226796B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:45:01+00:00'
last_modified: '2022-05-30T04:48:40.644069+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    d527:
      image_group_id: I1PD95943
      title: རྒྱུད་གཞན་གྲུབ་པ་ཞེས་བྱ་བའི་རབ་ཏུ་བྱེད་པ།
      total_pages: 1825
      order: 98
      base_file: d527.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
